# Generated by Django 6.1.1 on 2026-09-11 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=150)),
                ('institution', models.CharField(max_length=150)),
                ('period', models.CharField(max_length=50)),
                ('grade_or_details', models.CharField(blank=True, max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Education',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=120)),
                ('company', models.CharField(max_length=120)),
                ('location', models.CharField(blank=True, default='Bangalore, India', max_length=100)),
                ('start_date', models.CharField(max_length=50)),
                ('end_date', models.CharField(default='Present', max_length=50)),
                ('description', models.TextField()),
                ('technologies', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Alex Mercer', max_length=100)),
                ('tagline', models.CharField(default='Full Stack Engineer & Cloud Architect', max_length=200)),
                ('bio', models.TextField(default='Passionate Full-Stack Developer specializing in building high-performance web applications with Django, Python, React, and Google Cloud Platform.')),
                ('about_details', models.TextField(default='With hands-on experience designing robust relational databases, scalable microservices, and sleek user experiences, I turn complex technical challenges into elegant, production-grade solutions.')),
                ('years_of_experience', models.PositiveIntegerField(default=3)),
                ('completed_projects_count', models.PositiveIntegerField(default=18)),
                ('happy_clients_count', models.PositiveIntegerField(default=14)),
                ('location', models.CharField(default='Bangalore, India', max_length=100)),
                ('email', models.EmailField(default='developer@example.com', max_length=254)),
                ('phone', models.CharField(blank=True, default='+91 98765 43210', max_length=30)),
                ('github_url', models.URLField(blank=True, default='https://github.com')),
                ('linkedin_url', models.URLField(blank=True, default='https://linkedin.com')),
                ('twitter_url', models.URLField(blank=True, default='https://twitter.com')),
                ('resume_url', models.URLField(blank=True, default='#')),
                ('avatar_url', models.URLField(blank=True, default='https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('category', models.CharField(choices=[('all', 'All'), ('fullstack', 'Full Stack'), ('cloud', 'Cloud & DevOps'), ('backend', 'Backend & API'), ('frontend', 'Frontend UI')], default='fullstack', max_length=30)),
                ('short_description', models.CharField(max_length=255)),
                ('full_description', models.TextField()),
                ('tech_stack', models.CharField(help_text='Comma-separated technologies, e.g. Django, MySQL, React', max_length=255)),
                ('image_url', models.URLField(default='https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=800&q=80')),
                ('live_demo_url', models.URLField(blank=True, default='#')),
                ('github_url', models.URLField(blank=True, default='https://github.com')),
                ('is_featured', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('icon', models.CharField(default='code', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Skill Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('proficiency', models.PositiveIntegerField(default=85, help_text='Proficiency percentage (0-100)')),
                ('icon_class', models.CharField(blank=True, help_text='FontAwesome or Lucide icon class', max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='portfolio.skillcategory')),
            ],
            options={
                'ordering': ['order', '-proficiency'],
            },
        ),
    ]
