# Generated by Django 6.1.1 on 2026-09-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='grade_or_details',
            field=models.TextField(blank=True),
        ),
    ]
