# Generated by Django 6.1.1 on 2026-09-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_education_grade_or_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('all', 'All'), ('fullstack', 'Full Stack'), ('cloud', 'Cloud & DevOps'), ('backend', 'Backend & API'), ('frontend', 'Frontend UI'), ('gamedev', 'Game Dev')], default='fullstack', max_length=30),
        ),
    ]
